CREATE TABLE CONFIG(
   PARAM_KEY VARCHAR(64) PRIMARY KEY NOT NULL,
   PARAM_OBJECT VARCHAR(128)
);

CREATE TABLE PERSON(
   NAME VARCHAR(64) PRIMARY KEY NOT NULL,
   PIC VARCHAR(128),
   STATUS VARCHAR(10),
   FIRST_PRIZE VARCHAR(10),
   SECOND_PRIZE VARCHAR(10)
);
